export {default as Landing} from './Landing'
export {default as Bio} from './Bio'
export {default as Portfolio} from './Portfolio'
export {default as Skills} from './Skills'
// export {default as BlogPost} from './BlogPost'